### ISSUE TITLE
Quick Battle

### ISSUE THREAD

**Issue by samann** [cireficc/pokemon-arena-android#5]
Match two players in a room, and allow them to battle Pokemon (1v1 for now).

**Comment by samann** [comment]
- [x] #9 Battle Screen Attacks
- [x] #16 Implement Battle Engine
- [x] #21 Choose one Pokemon for battle
- [x] #26 Use GSON to send a JSON payload between clients
  - [x] #27 Create Serializable class for starting a match
  - [x] #33 Create Serializable class to send the result of using moves in a match
- [ ] #24 Damage reflected in health bar

These are the core issues for this task. We can close this issue if everything is working well even with #16 incomplete.
